Algoritmo "ATIVIDADE 7"
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
temperatura1: Inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Informe a temperatura ambiente")
leia(temperatura1)
se (temperatura1 <24)entao
se (temperatura1 <24) entao
 escreva("Está normal")
 senao
  escreva("Está normal")
  fimse
senao
se(temperatura1 <25)entao
 escreval("Está normal")
 senao
 escreval ("Muito quente")
 fimse
 fimse

Fimalgoritmo