Algoritmo "Atividade 12"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Noemy
// Data atual  : 08/08/2020
Var
// Seção de Declarações das variáveis 
idade: inteiro
dias: inteiro
horas: inteiro
Inicio
// Seção de Comandos
 escreva("Digite sua idade")
 leia(idade)
 dias<-idade*360
 horas<-dias*24
 escreval("dias:",dias)
 escreval("horas:",horas)

Fimalgoritmo