Algoritmo "Q3"

Var
nome: caractere
idade: inteiro
ano: inteiro
Inicio
 escreval("Digite seu nome")
 leia(nome)
 escreval("Digite sua idade")
 leia(idade)
 se(idade <=17) entao
 escreval ("Muito novo(a)")
 senao
 se (idade >= 18) entao
 escreval("Se for homem digite 65 e mulher 60, por favor")
 leia(ano)
 escreval("A multiplicação é:", ano-idade)

 escreval("Para você se aposentar falta", ano-idade)
 fimse
 FIMSE
Fimalgoritmo