Algoritmo "Question 2"

Var
Lv1: vetor [0..5] de inteiro
Lv2: vetor [0..5] de inteiro
Lv3: vetor [0..5] de inteiro
contador: inteiro

Inicio
para contador de 0 ate 5 faca
escreval("Digite a quantidade de livros")
leia(Lv1[contador])
fimpara

para contador de 0 ate 5 faca
escreval("Digite preços")
leia(Lv2[contador])
fimpara

para contador de 0 ate 5 faca
Lv3[contador] <-Lv1[contador] + Lv2[contador]
escreval (Lv3[contador])
fimpara

Fimalgoritmo